### ISSUE TITLE
Implement c++ solutions for sampling in txnsim()

### ISSUE THREAD

**Issue by jaymon0703** [braverock/blotter#101]
For sampling without replacement, random_shuffle from the Algorithm STL may be a viable solution. Dirk has documented an example using Rcpp at https://gallery.rcpp.org/articles/stl-random-shuffle/index.html.

For sampling with replacement, we may need to use [std::sample from c++17](https://en.cppreference.com/w/cpp/algorithm/sample), but this may not yet be supported in R (see below screenshot from https://gallery.rcpp.org/articles/rcpp-and-c++11-c++14-c++17/). If that is indeed still the case, we will need to explore another solution in c++.

![image](https://user-images.githubusercontent.com/4340156/65768113-4ee7ba80-e130-11e9-88b3-5936684f74d1.png)

Note, in `mcsim()` for replacement=TRUE we use `tsboot()` which may be difficult to speed-up. For replacement=FALSE, we use `sample()` which may be a candidate for speed-up. The focus for now will be on `txnsim()`.
For `txnsim()` we use `sample()` throughout...and i envisage most of the speed-up benefits to be lurking in that function. At least, i hope there will be. A simple benchmark of `randomShuffle()` and `sample()` shows at least a 30% speed-up benefit, which is significant enough to warrant further investigations.

![image](https://user-images.githubusercontent.com/4340156/65768864-73449680-e132-11e9-8a67-258bad0338aa.png)

Thanks @QuantDevHacks for the idea.

**Comment by jaymon0703** [comment]
I have created a local branch, 101_txnsim_speedup and made a few changes, as follows:

1. 
![image](https://user-images.githubusercontent.com/4340156/65800750-96456980-e177-11e9-8e73-c9643a597127.png)



2. 
![image](https://user-images.githubusercontent.com/4340156/65800637-49fa2980-e177-11e9-9a43-ddeff0b1d96f.png)

3. 
![image](https://user-images.githubusercontent.com/4340156/65800687-6eee9c80-e177-11e9-8335-646c5f9654da.png)

4. 
![image](https://user-images.githubusercontent.com/4340156/65800728-8af23e00-e177-11e9-8d6c-ab4d161989fa.png)

I get these `NOTE`s when running a `build check`

![image](https://user-images.githubusercontent.com/4340156/65800507-f4258180-e176-11e9-86d5-9245b6c9342b.png)

When testing the function with randomShuffle() from randomShuffle.cpp as opposed to sample() from base R i get the below error:

![image](https://user-images.githubusercontent.com/4340156/65800800-b70dbf00-e177-11e9-85f7-82fae7184d52.png)

This implies some outstanding configuration for the shared object...but at this point i am a bit stumped. I will come back to this tomorrow, hopefully, before i push the new local branch to a remote branch.

The NOTE mentions reviewing section 5 in this manual - http://www.math.ncu.edu.tw/~chenwc/R_note/reference/package/R-exts.pdf - and it appears section 5.5 may hold the key...

**Comment by jaymon0703** [comment]
For completeness, the .cpp file

![image](https://user-images.githubusercontent.com/4340156/65803756-ddcff380-e17f-11e9-8751-09706b7a89de.png)

Still getting similar error...

**Comment by joshuaulrich** [comment]
Hi Jasen.  Do you have profiling output of an example that demonstrates that the call to `sample()` is a bottleneck?  I ran some of the `mcsim()` examples, and `sample()` doesn't appear in the profiling results.  I would be surprised if it did, because `sample()` drops to C quickly.

```r
demo('longtrend', ask=FALSE)

set.seed(21)
Rprof()
nrsim <- mcsim("longtrend", "longtrend", n=1000,
    replacement=FALSE, l=1, gap=10, CI=0.95)
Rprof(NULL)
srp <- summaryRprof()
head(srp$by.total, 15)
                     total.time total.pct self.time self.pct
"mcsim"                   14.90    100.00      0.00     0.00
"tryCatch"                12.84     86.17      0.02     0.13
"tryCatchList"            12.84     86.17      0.02     0.13
"tryCatchOne"             12.82     86.04      0.04     0.27
"doTryCatch"              12.78     85.77      0.12     0.81
"apply"                   11.74     78.79      0.22     1.48
"FUN"                     11.60     77.85      0.12     0.81
"checkData"                9.88     66.31      0.06     0.40
"try"                      9.76     65.50      0.00     0.00
"as.xts"                   9.62     64.56      0.04     0.27
"as.xts.double"            9.58     64.30      0.08     0.54
"StdDev"                   8.32     55.84      0.02     0.13
"do.call"                  8.12     54.50      0.06     0.40
"as.POSIXct"               7.44     49.93      0.16     1.07
"as.POSIXct.default"       7.36     49.40      0.04     0.27
```

I encourage you to spend more time profiling.  Make sure you know where the bottleneck is before you spend time trying to optimize, and before adding a dependency.

**Comment by braverock** [comment]
I've also indicated that `mcsim` likely isn't a significant target for optimization.  I think `txnsim` would benefit more from an overall performance boost, but the issue might be in the sampling logic as much as in the R code.

**Comment by jaymon0703** [comment]
Hi Joshua. Thanks for the comment and profiling stats. I have profiled sample() with random_shuffle() using a small input vector and there appears to be 30% speed up on average. My next objective was to replace sample() for the simplest case in txnsim() with random_shuffle and ideally observe at least an equal improvement in performance in my local feature branch. I have gotten stuck trying to build the package without the note which mirrors the error I get. 

Calling sample() 10k times for example in txnsim may make testing a cpp alternative worthwhile. Also, future txnsim work may require more sophisticated and more frequent sampling. Its all exploratory at this stage.

**Comment by braverock** [comment]
Another thing we could consider would be sampling a much larger vector of indices, and then using that vector to look up round turn trades.

Josh is correct that we should profile `txnsim` and see where the time is actually being spent.

**Comment by jaymon0703** [comment]
Makes sense. I will profile txnsim and report my findings. Thanks Brian and Josh!

**Comment by joshuaulrich** [comment]
> My next objective was to replace sample() for the simplest case in txnsim() with random_shuffle and ideally observe at least an equal improvement in performance in my local feature branch.

I would only expect an equal improvement in `txnsim()` that used `random_shuffle()` if all of the time spent in `txnsim()` was in the call to `sample()`.  I doubt that's the case here.

I would expect only a small difference in overall performance from using a custom solution in place of `sample()`.  Using your data, a 50us speedup for 10,000 calls would save ~0.5s.  That's nice, but not a huge gain if the total runtime is < 5s.

----

EDIT: I just ran the example in `?txnsim` for `n = 10000`.

```r
require(blotter)
demo('longtrend',ask=FALSE)

Rprof()
out <- txnsim('longtrend', 10000, FALSE)
Rprof(NULL)
srp <- summaryRprof()
```

`sample` only appears 3 times.  Spending 50us less in those `sample()` calls will not noticeably improve performance.

```
> grep '"sample"' Rprof.out 
"sample.int" "sample" "subsample" "tradesample" "FUN" "lapply" "sapply" "replicate" "FUN" "lapply" "txnsim" 
"sample.int" "sample" "subsample" "tradesample" "FUN" "lapply" "sapply" "replicate" "FUN" "lapply" "txnsim" 
"sample" "subsample" "tradesample" "FUN" "lapply" "sapply" "replicate" "FUN" "lapply" "txnsim"
```

Not surprisingly, xts functions are at the top of the list of functions we're spending the most time in.

```r
lapply(srp[1:2], head, 10)
$by.self
                     self.time self.pct total.time total.pct
"make.names"              4.56    10.69       5.88     13.79
"merge.xts"               3.02     7.08      10.96     25.70
"strptime"                2.74     6.43       3.04      7.13
"as.POSIXct.POSIXlt"      1.36     3.19       1.86      4.36
".Call"                   1.10     2.58       1.10      2.58
"[.xts"                   1.08     2.53      10.04     23.55
"dim"                     0.76     1.78       0.80      1.88
"lapply"                  0.72     1.69      14.02     32.88
"$"                       0.72     1.69       1.66      3.89
"NextMethod"              0.72     1.69       0.74      1.74

$by.total
               total.time total.pct self.time self.pct
"txnsim"            42.64    100.00      0.00     0.00
"FUN"               19.04     44.65      0.42     0.98
"updatePortf"       18.20     42.68      0.06     0.14
"lapply"            14.02     32.88      0.72     1.69
"["                 11.36     26.64      0.32     0.75
"merge.xts"         10.96     25.70      3.02     7.08
".updatePosPL"      10.20     23.92      0.24     0.56
"[.xts"             10.04     23.55      1.08     2.53
"cbind"              8.96     21.01      0.04     0.09
"sapply"             7.78     18.25      0.30     0.70
```

**Comment by jaymon0703** [comment]
Thanks Josh. Your findings are very helpful. My initial optimism about the potential for speed-up was based on Jonathan Olmsted's post [here](http://www.olmjo.com/blog/2013/05/13/rcpp-updates/) and the [accept-reject sampler using RcppArmadillo::sample()](https://gallery.rcpp.org/articles/an-example-of-using-Rcpp-sample/).

Premature optimization aside, i was equally optimistic about learning extending R packages with Rcpp and cpp in general.

**Comment by jaymon0703** [comment]
Below are my results from running the same function through `Rprof` and `sample` is indeed not in the top 10 functions. I could not find it even in the top 100 functions.

At this point i am leaning towards closing this specific issue. @QuantDevHacks has shared a [c++ project](https://github.com/QuantDevHacks/TxnSimCppFirstPrototype/tree/Dev) for doing round turn trade simulation in c++ which i am yet to test. Perhaps its the beginning of a complete c++ port of `txnsim`.

````r
lapply(srp[1:2], head, 10)

$by.self
                     self.time self.pct total.time total.pct
"make.names"            402.02    40.08     454.56     45.31
"merge.xts"             213.98    21.33     691.00     68.88
"make.unique"            36.50     3.64      36.50      3.64
"updatePortf"            20.78     2.07     186.46     18.59
"strptime"               18.12     1.81      21.10      2.10
".Call"                  12.28     1.22      12.28      1.22
"paste"                   9.86     0.98      16.20      1.61
"vapply"                  8.44     0.84      10.54      1.05
"NextMethod"              7.82     0.78       8.02      0.80
"as.POSIXct.POSIXlt"      7.68     0.77      11.80      1.18

$by.total
               total.time total.pct self.time self.pct
"txnsim"          1003.14    100.00      0.16     0.02
"merge.xts"        691.00     68.88    213.98    21.33
"cbind"            681.88     67.97      0.98     0.10
"make.names"       454.56     45.31    402.02    40.08
"updatePortf"      186.46     18.59     20.78     2.07
"FUN"              165.88     16.54      3.46     0.34
"lapply"           119.38     11.90      6.08     0.61
"["                 95.24      9.49      3.80     0.38
".updatePosPL"      93.64      9.33      4.76     0.47
"[.xts"             81.98      8.17      7.42     0.74

```
