### ISSUE TITLE
Error installing quanstrat R version 4.0.2

### ISSUE THREAD

**Issue by financeguy72** [braverock/blotter#108]
Hi I tried to run the code below and I got this error at the end:

install.packages("FinancialInstrument") # dependency
install.packages("PerformanceAnalytics") # dependency
library("FinancialInstrument")
library("PerformanceAnalytics")
install.packages("devtools")
library(devtools)
install_github("braverock/blotter",force= T) # dependency
library("blotter")  
install_github("braverock/quantstrat", force=T)
>install_github("braverock/quantstrat", force=T)
Downloading GitHub repo braverock/quantstrat@master
√  checking for file 'C:\Users\Isaac\AppData\Local\Temp\Rtmp82VJX0\remotes1b042174a16\braverock-quantstrat-b00b026/DESCRIPTION' (699ms)
-  preparing 'quantstrat': (2.6s)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (1.9s)
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
     NB: this package now depends on R (>= 3.5.0)
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: 'quantstrat/data/AAPL.rda'  'quantstrat/data/luxor.wfa.ples.RData'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: 'quantstrat/luxor.wfa.ples.RData'
-  building 'quantstrat_0.16.7.tar.gz'
   
Installing package into ‘C:/Users/Isaac/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'quantstrat' ...
** using staged installation
** libs

*** arch - i386
"C:/rtools40/mingw32/bin/"gcc  -I"C:/PROGRA~1/R/R-40~1.0/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c firstCross.c -o firstCross.o
"C:/rtools40/mingw32/bin/"gcc  -I"C:/PROGRA~1/R/R-40~1.0/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c init.c -o init.o
C:/rtools40/mingw32/bin/gcc -shared -s -static-libgcc -o quantstrat.dll tmp.def firstCross.o init.o -LC:/PROGRA~1/R/R-40~1.0/bin/i386 -lR
installing to C:/Users/Isaac/Documents/R/win-library/4.0/00LOCK-quantstrat/00new/quantstrat/libs/i386

*** arch - x64
"C:/rtools40/mingw64/bin/"gcc  -I"C:/PROGRA~1/R/R-40~1.0/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c firstCross.c -o firstCross.o
"C:/rtools40/mingw64/bin/"gcc  -I"C:/PROGRA~1/R/R-40~1.0/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c init.c -o init.o
C:/rtools40/mingw64/bin/gcc -shared -s -static-libgcc -o quantstrat.dll tmp.def firstCross.o init.o -LC:/PROGRA~1/R/R-40~1.0/bin/x64 -lR
installing to C:/Users/Isaac/Documents/R/win-library/4.0/00LOCK-quantstrat/00new/quantstrat/libs/x64
** R
** data
** demo
** inst
** byte-compile and prepare package for lazy loading
Error: (convertido del aviso) package 'foreach' was built under R version 4.0.2
Ejecución interrumpida
ERROR: lazy loading failed for package 'quantstrat'
* removing 'C:/Users/Isaac/Documents/R/win-library/4.0/quantstrat'
Error: Failed to install 'quantstrat' from GitHub:
  (convertido del aviso) installation of package ‘C:/Users/Isaac/AppData/Local/Temp/Rtmp82VJX0/file1b045aad5cc1/quantstrat_0.16.7.tar.gz’ had non-zero exit status

I didnt had any problem running the first codes, but my trouble was with the last one. Can someone help me please

**Comment by jaymon0703** [comment]
Hi @financeguy72 that error implies you need to install R 4.0.2. Do you mind upgrading your R version and reporting back?

**Comment by financeguy72** [comment]
Now it shows this error:

> install_github("braverock/blotter",force= T) # dependency
Downloading GitHub repo braverock/blotter@master
√  checking for file 'C:\Users\Isaac\AppData\Local\Temp\RtmpsL9MpN\remotes39dc68dd4cde\braverock-blotter-2393616/DESCRIPTION' (691ms)
-  preparing 'blotter': (1.3s)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (904ms)
-  checking for empty or unneeded directories
-  building 'blotter_0.15.0.tar.gz'
   
Installing package into ‘C:/Users/Isaac/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
ERROR: failed to lock directory 'C:/Users/Isaac/Documents/R/win-library/4.0' for modifying
Try removing 'C:/Users/Isaac/Documents/R/win-library/4.0/00LOCK-blotter'
Error: Failed to install 'blotter' from GitHub:
  (convertido del aviso) installation of package ‘C:/Users/Isaac/AppData/Local/Temp/RtmpsL9MpN/file39dc5deb434c/blotter_0.15.0.tar.gz’ had non-zero exit status

> install_github("braverock/quantstrat", force=T)
Downloading GitHub repo braverock/quantstrat@master
√  checking for file 'C:\Users\Isaac\AppData\Local\Temp\RtmpsL9MpN\remotes39dc3d607cfe\braverock-quantstrat-b00b026/DESCRIPTION' (514ms)
-  preparing 'quantstrat': (2.2s)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (1.6s)
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
     NB: this package now depends on R (>= 3.5.0)
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: 'quantstrat/data/AAPL.rda'  'quantstrat/data/luxor.wfa.ples.RData'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: 'quantstrat/luxor.wfa.ples.RData'
-  building 'quantstrat_0.16.7.tar.gz'
   
Installing package into ‘C:/Users/Isaac/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'quantstrat' ...
** using staged installation
** libs

*** arch - i386
"C:/rtools40/mingw32/bin/"gcc  -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c firstCross.c -o firstCross.o
"C:/rtools40/mingw32/bin/"gcc  -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c init.c -o init.o
C:/rtools40/mingw32/bin/gcc -shared -s -static-libgcc -o quantstrat.dll tmp.def firstCross.o init.o -LC:/PROGRA~1/R/R-40~1.2/bin/i386 -lR
installing to C:/Users/Isaac/Documents/R/win-library/4.0/00LOCK-quantstrat/00new/quantstrat/libs/i386

*** arch - x64
"C:/rtools40/mingw64/bin/"gcc  -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c firstCross.c -o firstCross.o
"C:/rtools40/mingw64/bin/"gcc  -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c init.c -o init.o
C:/rtools40/mingw64/bin/gcc -shared -s -static-libgcc -o quantstrat.dll tmp.def firstCross.o init.o -LC:/PROGRA~1/R/R-40~1.2/bin/x64 -lR
installing to C:/Users/Isaac/Documents/R/win-library/4.0/00LOCK-quantstrat/00new/quantstrat/libs/x64
** R
** data
** demo
** inst
** byte-compile and prepare package for lazy loading
Error: package 'blotter' required by 'quantstrat' could not be found
Ejecución interrumpida
ERROR: lazy loading failed for package 'quantstrat'
* removing 'C:/Users/Isaac/Documents/R/win-library/4.0/quantstrat'
Error: Failed to install 'quantstrat' from GitHub:
  (convertido del aviso) installation of package ‘C:/Users/Isaac/AppData/Local/Temp/RtmpsL9MpN/file39dc69e77f9/quantstrat_0.16.7.tar.gz’ had non-zero exit status

**Comment by braverock** [comment]
With things like this, you need to follow the errors very closely:

    ERROR: failed to lock directory 'C:/Users/Isaac/Documents/R/win-library/4.0' for modifying

suggests that either another R installer was running, or the user RStudio is running as doesn't have enough permissions to write to that directory, or the directory is read-only.

**Comment by jaymon0703** [comment]
You want to delete that lock file (`00LOCK-blotter`) before trying again - `Try removing 'C:/Users/Isaac/Documents/R/win-library/4.0/00LOCK-blotter'`

Generally that happens when a package fails to install properly. You should probably remove `force=TRUE` as well...you only want to re-install if the remote has changed.

**Comment by jaymon0703** [comment]
Hi @financeguy72 did the above resolve your issue?

**Comment by financeguy72** [comment]
I think its already working, I deleted the file (00LOCK-blotter) and I think it solved the problem, it showed me the following output:
 install_github("braverock/blotter") # dependency
Skipping install of 'blotter' from a github remote, the SHA1 (23936165) has not changed since last install.
  Use `force = TRUE` to force installation
> install_github("braverock/blotter", force = T) 
Downloading GitHub repo braverock/blotter@master
√  checking for file 'C:\Users\Isaac\AppData\Local\Temp\Rtmp2PkkRd\remotesccc4f62715e\braverock-blotter-2393616/DESCRIPTION' (1.7s)
-  preparing 'blotter': (1.9s)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (1.6s)
-  checking for empty or unneeded directories
-  building 'blotter_0.15.0.tar.gz'
   
Installing package into ‘C:/Users/Isaac/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'blotter' ...
** using staged installation
** libs

*** arch - i386
"C:/rtools40/mingw32/bin/"gcc  -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c calcPosAvgCost.c -o calcPosAvgCost.o
"C:/rtools40/mingw32/bin/"gcc  -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c init.c -o init.o
C:/rtools40/mingw32/bin/gcc -shared -s -static-libgcc -o blotter.dll tmp.def calcPosAvgCost.o init.o -LC:/PROGRA~1/R/R-40~1.2/bin/i386 -lR
installing to C:/Users/Isaac/Documents/R/win-library/4.0/00LOCK-blotter/00new/blotter/libs/i386

*** arch - x64
"C:/rtools40/mingw64/bin/"gcc  -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c calcPosAvgCost.c -o calcPosAvgCost.o
"C:/rtools40/mingw64/bin/"gcc  -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c init.c -o init.o
C:/rtools40/mingw64/bin/gcc -shared -s -static-libgcc -o blotter.dll tmp.def calcPosAvgCost.o init.o -LC:/PROGRA~1/R/R-40~1.2/bin/x64 -lR
installing to C:/Users/Isaac/Documents/R/win-library/4.0/00LOCK-blotter/00new/blotter/libs/x64
** R
** data
*** moving datasets to lazyload DB
** demo
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'blotter'
    finding HTML links ... done
    ABC                                     html  
    AcctReturns                             html  
    ArrivalCost                             html  
    IBM                                     html  
    IndexAdjustedCost                       html  
    IndexCost                               html  
    PortfReturns                            html  
    acOptTxns                               html  
    addAcctTxn                              html  
    addDiv                                  html  
    addPortfInstr                           html  
    addTxn                                  html  
    amzn                                    html  
    benchTradePerf                          html  
    benchTradeStats                         html  
    blotter-package                         html  
    calcPortfWgt                            html  
    calcPosAvgCost                          html  
    calcTxnAvgCost                          html  
    calcTxnValue                            html  
    chart.ME                                html  
    chart.Posn                              html  
    chart.Reconcile                         html  
    chart.Spread                            html  
    dailyTxnPL                              html  
    extractTxns                             html  
    getAccount                              html  
    getByPortf                              html  
    getBySymbol                             html  
    getEndEq                                html  
    getPortfAcct                            html  
    getPortfolio                            html  
    getPos                                  html  
    getPosAvgCost                           html  
    getPosQty                               html  
    getTxns                                 html  
    hist.mcsim                              html  
    hist.txnsim                             html  
    iStarPostTrade                          html  
Rd warning: C:/Users/Isaac/AppData/Local/Temp/RtmpiCm8aC/R.INSTALL46073b57f8d/blotter/man/iStarPostTrade.Rd:138: file link 'sd.annualized' in package 'PerformanceAnalytics' does not exist and so has been treated as a topic
    iStarSensitivity                        html  
    impShortfall                            html  
    initAcct                                html  
    initPortf                               html  
    initPosPL                               html  
    initSummary                             html  
    initTxn                                 html  
    is.account                              html  
    is.portfolio                            html  
    mcsim                                   html  
    pennyPerShare                           html  
    perTradeStats                           html  
    plot.iStarEst                           html  
    plot.iStarSens                          html  
    plot.mcsim                              html  
    plot.txnsPerf                           html  
    plot.txnsim                             html  
    print.txnsStats                         html  
    put.account                             html  
    put.portfolio                           html  
    quantile.mcsim                          html  
    quantile.txnsim                         html  
    summary.mcsim                           html  
    summary.txnsPerf                        html  
    summary.txnsim                          html  
    tradeQuantiles                          html  
    tradeStats                              html  
    trdPrcPerf                              html  
    txnsim                                  html  
    txnsim.portfs                           html  
    txnsim.portnames                        html  
    txnsim.txns                             html  
    updateAcct                              html  
    updateEndEq                             html  
    updatePortf                             html  
    updatePosPL                             html  
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
* DONE (blotter)
> library("braverock/blotter")  
Error in library("braverock/blotter") : 
  there is no package called ‘braverock/blotter’
> library("blotter")  
> install_github("braverock/quantstrat")
Downloading GitHub repo braverock/quantstrat@master
√  checking for file 'C:\Users\Isaac\AppData\Local\Temp\Rtmp2PkkRd\remotesccc36175469\braverock-quantstrat-b00b026/DESCRIPTION' (655ms)
-  preparing 'quantstrat': (2.4s)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (2.3s)
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
     NB: this package now depends on R (>= 3.5.0)
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: 'quantstrat/data/AAPL.rda'  'quantstrat/data/luxor.wfa.ples.RData'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: 'quantstrat/luxor.wfa.ples.RData'
-  building 'quantstrat_0.16.7.tar.gz'
   
Installing package into ‘C:/Users/Isaac/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'quantstrat' ...
** using staged installation
** libs

*** arch - i386
"C:/rtools40/mingw32/bin/"gcc  -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c firstCross.c -o firstCross.o
"C:/rtools40/mingw32/bin/"gcc  -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c init.c -o init.o
C:/rtools40/mingw32/bin/gcc -shared -s -static-libgcc -o quantstrat.dll tmp.def firstCross.o init.o -LC:/PROGRA~1/R/R-40~1.2/bin/i386 -lR
installing to C:/Users/Isaac/Documents/R/win-library/4.0/00LOCK-quantstrat/00new/quantstrat/libs/i386

*** arch - x64
"C:/rtools40/mingw64/bin/"gcc  -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c firstCross.c -o firstCross.o
"C:/rtools40/mingw64/bin/"gcc  -I"C:/PROGRA~1/R/R-40~1.2/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign -c init.c -o init.o
C:/rtools40/mingw64/bin/gcc -shared -s -static-libgcc -o quantstrat.dll tmp.def firstCross.o init.o -LC:/PROGRA~1/R/R-40~1.2/bin/x64 -lR
installing to C:/Users/Isaac/Documents/R/win-library/4.0/00LOCK-quantstrat/00new/quantstrat/libs/x64
** R
** data
** demo
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'quantstrat'
    finding HTML links ... done
    AAPL                                    html  
    SharpeRatio.deflated                    html  
    SharpeRatio.haircut                     html  
    add.distribution                        html  
    add.distribution.constraint             html  
    add.indicator                           html  
    add.init                                html  
    add.rule                                html  
    add.signal                              html  
    addOrder                                html  
    addPosLimit                             html  
    apply.paramset                          html  
    apply.paramset.signal.analysis          html  
    applyIndicatorSignals                   html  
    applyIndicators                         html  
    applyParameter                          html  
    applyRules                              html  
    applySignals                            html  
    applyStrategy                           html  
    applyStrategy.rebalancing               html  
    beanplot.signals                        html  
    chart.forward                           html  
    chart.forward.training                  html  
    clone.orderbook                         html  
    clone.portfolio                         html  
    degrees.of.freedom                      html  
    delete.paramset                         html  
    distributional.boxplot                  html  
    dotprofitHurdle                         html  
    enable.rule                             html  
    get.strategy                            html  
    getOrderBook                            html  
    getOrders                               html  
    getParameterTable                       html  
    getPosLimit                             html  
    initOrders                              html  
    initStrategy                            html  
    initSymbol                              html  
    install.param.combo                     html  
    is.strategy                             html  
    load.strategy                           html  
    luxoraudit                              html  
    match.names                             html  
    osMaxPos                                html  
    osNoOp                                  html  
    paramConstraint                         html  
    portfolio.luxor                         html  
    post.signal.returns                     html  
    print.dof                               html  
    print.haircutSR                         html  
    print.profitHurdle                      html  
    profitHurdle                            html  
    put.orderbook                           html  
    put.strategy                            html  
    quantstrat-package                      html  
    rm.strat                                html  
    ruleOrderProc                           html  
    rulePctEquity                           html  
    ruleRevoke                              html  
    ruleSignal                              html  
Rd warning: C:/Users/Isaac/AppData/Local/Temp/RtmpqgCjrG/R.INSTALL26bc20e62de/quantstrat/man/ruleSignal.Rd:54: file link 'getPrice' in package 'quantmod' does not exist and so has been treated as a topic
Rd warning: C:/Users/Isaac/AppData/Local/Temp/RtmpqgCjrG/R.INSTALL26bc20e62de/quantstrat/man/ruleSignal.Rd:93: file link 'getPrice' in package 'quantmod' does not exist and so has been treated as a topic
Rd warning: C:/Users/Isaac/AppData/Local/Temp/RtmpqgCjrG/R.INSTALL26bc20e62de/quantstrat/man/ruleSignal.Rd:96: file link 'getPrice' in package 'quantmod' does not exist and so has been treated as a topic
    sample_random_multests                  html  
    save.strategy                           html  
    setParameterConstraint                  html  
    setParameterDistribution                html  
    sigComparison                           html  
    sigCrossover                            html  
    sigFormula                              html  
    sigPeak                                 html  
    sigThreshold                            html  
    sigTimestamp                            html  
Rd warning: C:/Users/Isaac/AppData/Local/Temp/RtmpqgCjrG/R.INSTALL26bc20e62de/quantstrat/man/sigTimestamp.Rd:16: file link 'split.xts' in package 'xts' does not exist and so has been treated as a topic
Rd warning: C:/Users/Isaac/AppData/Local/Temp/RtmpqgCjrG/R.INSTALL26bc20e62de/quantstrat/man/sigTimestamp.Rd:18: file link '.indexday' in package 'xts' does not exist and so has been treated as a topic
    signal.generate.statistics              html  
    signal.obj.slope                        html  
    signal.path.plot                        html  
    signal.plot                             html  
    spx                                     html  
    stats                                   html  
    stratBBands                             html  
    stratFaber                              html  
    strategy                                html  
    tradeGraphs                             html  
    tradeOrderStats                         html  
    updateOrders                            html  
    updateStrategy                          html  
    finding level-2 HTML links ... done

    walk.forward                            html  
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
* DONE (quantstrat)
> library("quantstrat")
Loading required package: foreach
> library("quantstrat")

I needed to force the installation of install_github("braverock/blotter", force = T) but after that it seems is working fine both packages, I just dont know why it showed me the last message:
 > library("quantstrat")
Loading required package: foreach

**Comment by jaymon0703** [comment]
Glad it’s working then. Please close the issue if you are satisfied and have no more questions.

**Comment by financeguy72** [comment]
THANKS
