### ISSUE TITLE
Issue with `perTradeStats`

### ISSUE THREAD

**Issue by dancju** [braverock/blotter#111]
I got the following error message when calling `perTradeStats`.

```
> perTradeStats(strPort, "NG")
Error in idx[] <- idx[0] : replacement has length zero
> traceback()
2: Ops.xts(Cum.PL/abs(trades$Max.Pos[i]), tick_value)
1: perTradeStats(strPort, "NG")
> 
```

<img width="400" alt="Screen Shot 2021-05-27 at 6 41 50 PM" src="https://user-images.githubusercontent.com/3108734/119917440-1a0bb680-bf56-11eb-877c-b804826481f9.png">

**Comment by jaymon0703** [comment]
Thanks for the report. Can you include a minimum reproducible example please? I suspect there is no "NG" symbol in your environment or it is empty?

**Comment by dancju** [comment]
@jaymon0703 Thank you for your instant reply!

No, I don't think "NG" is the issue here.

Here is my script so you can reproduce it.

https://gist.github.com/nerddan/4b73a8d16a3503c04978d52af460c832

**Comment by jaymon0703** [comment]
tick_value is empty...still looking why

![image](https://user-images.githubusercontent.com/4340156/119919823-3d743880-bf39-11eb-8e08-a09db2bf286c.png)

**Comment by jaymon0703** [comment]
tick_size is NULL...i suspect the warning message from creating the future is a sign of the problem

![image](https://user-images.githubusercontent.com/4340156/119920049-a22f9300-bf39-11eb-9d94-945923a5608f.png)

**Comment by jaymon0703** [comment]
From the docs...you need to specify your tick_size...

```r
future(primary_id, currency, multiplier, tick_size = NULL,
  identifiers = NULL, assign_i = TRUE, overwrite = TRUE, ...,
  underlying_id = NULL)
 ```

**Comment by jaymon0703** [comment]
Warning message is not the issue...i was wrong

![image](https://user-images.githubusercontent.com/4340156/119920322-271aac80-bf3a-11eb-80d4-403e137acab2.png)

Hope this helps.

**Comment by dancju** [comment]
@jaymon0703 Thank you so much! Specifying `tick_size` solves this problem. But still don't see which part of the doc says `tick_size` is mandatory.

**Comment by jaymon0703** [comment]
This will do - `future(strSymbol, strCurrency, 1e4, tick_size=1)` or whatever your tick size is for NG - sorry for the spammy comments...just thinking out loud

**Comment by jaymon0703** [comment]
Well, its not mandatory i suppose hence the default of NULL...but when used in perTradeStats i guess it is mandatory by current design...so will likely require a code change in perTradeStats...

**EDIT** - might make sense to change the future function...thoughts @braverock?
