### ISSUE TITLE
AddAcctTxn vs. AddTxn (Additions and Withdrawals)

### ISSUE THREAD

**Issue by untdacca** [braverock/blotter#120]
I have a mock table (final_trades) of trades, additions, and withdrawals I am trying to update within the blotter. The issue is several "additions/withdrawals" are symbols (ZIL) and not pairs (ZILBUSD) making it difficult to reconcile trades across different pairs. The goal is to either 1) add additions/withdraws separately with AddAccTxn or 2) add additions/withdrawals dynamically with AddTxn

Going with solution 2):

The table final_trades combines historical trades, deposits, and withdrawals. Deposits of ZIL are traded across two pairs, ZILBUSD and ZILUSD.

Initially, I was treating each ZIL addition/withdrawal as the pair ZILBUSD, so all transactions appeared within ZILBUSD's transaction history. 

However, this is incorrect because subsequent trades are made with the ZILUSD pair.

Set 1.1 to 1.3 reconciles because the 3rd trade was made with ZILBUSD. Set 2 does not reconcile because Set 2.4 buys ZILUSD while Set 2.5 (withdraws) ZILBUSD. This is happening because I am basically treating each deposit/withdrawal of ZIL as a buy/sell transaction within ZILBUSD (the problem, is fix addAccTxn or suffer with AddTxn). Using Set 3 as another example, Set 3.6 purchases ZILUSD however Set 3.7  (withdraws) ZILBUSD.

Any ideas on how to update the symbol ZIL to either ZILUSD or ZILBUSD based on what is subsequently traded? As you can imagine the issue gets worse with ambiguous symbols like ETH.

Thinking about solution 1):

I am able to add each symbol's USD equivalent as an addition/withdrawal, however, this does not affect trading out of a position like ZILUSD. Even though a "USD" deposit has been made, the pair ZILBUSD will sell short since there is no initial pair ZIL
 
Notes:
1) I have turned each symbol into a currency (ZIL is a USD-based currency) ie ```{r} currency(i, currency = 'USD', tick_size = NULL , assign_i = TRUE, overwrite = TRUE)  ```
2) I have turned each pair into an instrument (ZILUSD and ZILBUSD are instruments based on the currency USD) ie ```{r} instrument(i, currency = 'USD', multiplier = 1, tick_size = NULL, identifiers = NULL, type = 'unknown', assign_i = TRUE, overwrite = TRUE) ```

**Comment by braverock** [comment]
Accounts are in a single currency, not a pair.  Typically you have a Account currency, like USD, that you want to convert everything to to understand the Account value.

it is fine to have each coin be a currency instrument, but the currency should be e.g. 'ZIL', not 'USD'

each pair is an exchange_rate instrument, that contains two currencies.

then everything should work with additions/withdrawals of single currencies, and trades in exchange rate pairs.

**Comment by Fayorsey** [comment]
@braverock Understood. Coins have been turned into currencies and pairs into exchange rates. I've also switched from AddTxn to AddAcctTxn when recording an addition or withdrawal.

I'm now running into the error:
```
Error in if (length(CcyMult) == 1 && CcyMult == 1) { : 
  missing value where TRUE/FALSE needed
```
I believe this is from either updateAcct or updatePosPL. The error occurred for the pair BUSDUSD ( currency = USD, countercurrency = BUSD). Code blocks of 1) the currency and instrument creation and 2) entire blotter are below. TY

<img width="360" alt="Screen Shot 2023-04-06 at 4 40 15 PM" src="https://user-images.githubusercontent.com/76915445/230500739-431bfa2d-7dbc-4d3e-a86c-ac63c34e4660.png">


```
exchange_info <- binance_exchange_info()$symbols
coins <- binance_coins()
coins <- coins[-1]

rm_instruments()
rm_currencies()




# Currenies (ie. USD, USDT, USD4, BUSD, ZIL, etc)
all_currencies <- sort(unique(c(coins, exchange_info$baseAsset, exchange_info$quoteAsset)))

currencies <- foreach(i = all_currencies) %do% {
  currency(i, tick_size = NULL , assign_i = TRUE, overwrite = TRUE)
}


instruments <- foreach(i = 1:nrow(exchange_info), .errorhandling = 'remove') %do% {
  exchange_rate(exchange_info[i,]$symbol, currency = exchange_info[i,]$quoteAsset, counter_currency = exchange_info[i,]$baseAsset, tick_size = NULL,
             identifiers = NULL, assign_i = TRUE, overwrite = TRUE)
}
```

Blotter setup
```
# Set up a portfolio object and an account object in blotter
initDate = '2021-01-01'
initEq = 10000

print("Initializing portfolio and account structure")
ltportfolio = 'longtrend'
ltaccount = 'longtrend'

initPortf(ltportfolio, symbols, initDate = initDate, currency = 'USDT')
initAcct(ltaccount, portfolios = 'longtrend', initDate = initDate, initEq = initEq)
verbose = TRUE

# Create trades

combined_trades <- all_trades %>%
  dplyr::select(-id, -order_list_id, -is_maker, -is_best_match) %>%
  dplyr::group_by(symbol, order_id, commission_asset, time, is_buyer) %>%
  dplyr::rename(TxnPrice = price, TxnQty = qty, TxnFees = commission, TxnDate = time) %>% 
  dplyr::summarise(TxnPrice = mean(as.numeric(TxnPrice)), TxnQty = sum(as.numeric(TxnQty)),
                   TxnAmount = sum(as.numeric(quote_qty)), TxnFees = sum(as.numeric(TxnFees)),
                   TxnType = 'Trade') %>%
  dplyr::arrange(TxnDate)


final_trades <- combined_trades %>% full_join(transfers)
final_trades <- final_trades %>% arrange(TxnDate)


for (i in 1:nrow(final_trades)) { 
  
  CurrentDate = as.xts(final_trades$TxnDate[i])
  cat(".")
  # equity = getEndEq(ltaccount, CurrentDate)*.01
  ClosePrice = as.numeric(final_trades[i,]$TxnPrice)
  UnitSize = as.numeric(final_trades[i,]$TxnQty)
  
  # Check if TxnType is Trade
  if (final_trades[i,]$TxnType == 'Trade' ) {
    # If buying 
    if (final_trades[i,]$is_buyer == TRUE) { 
      cat('\n')
      # Store trade with blotter
      addTxn(ltportfolio, Symbol = final_trades[i,]$symbol , TxnDate = CurrentDate, TxnPrice = ClosePrice, TxnQty = UnitSize , TxnFees = 0, verbose = verbose)
    } else {
      # If selling
      if (final_trades[i,]$is_buyer == FALSE) {
        # Check if current position is zero or less that amount trying to sell
        # (this was suppose to prevent short selling since I am unable to figure out deposits/withdrawals using addAccTxn)
        # Posn = getPosQty(ltportfolio, Symbol = final_trades[i, ]$symbol, Date = CurrentDate)
        # if ( Posn == 0 | (Posn < UnitSize )) {
        #   # Store trade with blotter
        #   cat('\n')
        #   addTxn(ltportfolio, Symbol = final_trades[i, ]$symbol, TxnDate = CurrentDate, TxnPrice = ClosePrice, TxnQty = UnitSize, TxnFees = 0, verbose = verbose)
        # }
        # Store trade with blotter
        cat('\n')
        addTxn(ltportfolio, Symbol = final_trades[i, ]$symbol, TxnDate = CurrentDate, TxnPrice = ClosePrice, TxnQty = -UnitSize , TxnFees = 0, verbose = verbose)
      }
    }
    updatePortf(ltportfolio, Symbols = final_trades[i,]$symbol, Prices = get(final_trades[i,]$symbol)[,"open"])
  } else {
    #Find the first pair using quoted asset (ie, ZIL pairs are ZILBUSD, ZILUSD in the environment) 
    # (this is the problem, I am grabbing the first pair as oppose to "dynamically" selecting what is traded next)
    # TxnSymbol <- ls(globalenv())[grep(paste0(paste0(final_trades[i,]$symbol,'.*USD'), paste0('|USD.*',final_trades[i,]$symbol)), ls(globalenv()))][1]
    # Check if TxnType is Additions
    if (final_trades[i,]$TxnType == "Additions") {
      # Store trade with blotter
      cat('\n')
      addAcctTxn(ltaccount, TxnDate = CurrentDate, TxnType = final_trades[i,]$TxnType, Amount = final_trades[i,]$TxnAmount, verbose = verbose)
    } else {
      # Check if TxnType is Withdrawals
      if (final_trades[i,]$TxnType == "Withdrawals") {
        # Store trade with blotter
        cat('\n')
        addAcctTxn(ltaccount, TxnDate = CurrentDate, TxnType = final_trades[i,]$TxnType, Amount = final_trades[i,]$TxnAmount, verbose = verbose)
      }
    }
  }
  
  # Calculate P&L and Equity with blotter
  updateAcct(ltaccount)
  updateEndEq(ltaccount)
}
```

**Comment by Fayorsey** [comment]
@braverock appreciate your help. I'm currently running into the error:

Error in if (length(CcyMult) == 1 && CcyMult == 1) { : 
  missing value where TRUE/FALSE needed

I believe it is caused by one of the currency pairs during updateAcct or updatePosPL. Any idea what would cause missing values to occur?

**Comment by braverock** [comment]
are all the currencies defined?  e.g.

```
currency('USD','US Dollar')
currency('USDC','Circle USD Coin')
currency('BTC','Bitcoin')
```

**Comment by Fayorsey** [comment]
Yes, I have 181 currencies defined.
<img width="559" alt="Screen Shot 2023-04-13 at 9 47 35 AM" src="https://user-images.githubusercontent.com/76915445/231779087-2030072c-596e-43aa-9b2c-2d2fc98d1c12.png">

I've also been struggling to get additions/withdrawals to appear in the summary table. Currently, they are in the account$Additions and account$Withdrawals table, however, the main account$summary table does not update with these values at all. I believe this has something to do with how im using 

```
updateAcct(ltaccount)
updateEndEq(ltaccount)
```

When I leave it as above, only some of my trades are included in the blotter and several of my initial transactions are just not included. When I include ``` updateAcct(ltaccount, Dates = CurrentDate) updateEndEq(ltaccount, Dates = CurrentDate)``` the summary table never gathers any data past the initial row.

Example of additions in the account$Additions table
<img width="208" alt="Screen Shot 2023-04-13 at 9 53 03 AM" src="https://user-images.githubusercontent.com/76915445/231781203-e5b07f6f-d01d-433f-b6c6-f8cd2b080fcf.png">

Example of additions/withdrawals not appearing in the account$summary table, and trades being recorded several months after I started trading (ie first trade was Feb 21, 2022, first recorded traded was March 2, 2023).
<img width="1032" alt="Screen Shot 2023-04-13 at 9 59 22 AM" src="https://user-images.githubusercontent.com/76915445/231782592-b02239fd-7eb7-4132-9bdc-3a0da76198a9.png">

Screenshot of my transaction data
<img width="999" alt="Screen Shot 2023-04-13 at 9 50 05 AM" src="https://user-images.githubusercontent.com/76915445/231783175-6e29a94b-3d30-47fa-aca2-4415b28328a1.png">


Full code below:

```

currencies <- foreach(i = all_currencies) %do% {
  currency(i, tick_size = NULL , assign_i = TRUE, overwrite = TRUE)
}


instruments <- foreach(i = 1:nrow(exchange_info), .errorhandling = 'remove') %do% {
  exchange_rate(exchange_info[i,]$symbol, currency = exchange_info[i,]$quoteAsset, counter_currency = exchange_info[i,]$baseAsset, tick_size = NULL,
             identifiers = NULL, assign_i = TRUE, overwrite = TRUE)
}

# Set up a portfolio object and an account object in blotter
initDate = '2021-01-01'
initEq = 10000

print("Initializing portfolio and account structure")
ltportfolio = 'longtrend'
ltaccount = 'longtrend'

initPortf(ltportfolio, symbols, initDate = initDate, currency = 'USD')
initAcct(ltaccount, portfolios = 'longtrend', initDate = initDate, initEq = initEq)
verbose = TRUE

# Create trades

combined_trades <- all_trades %>%
  dplyr::select(-id, -order_list_id, -is_maker, -is_best_match) %>%
  dplyr::group_by(symbol, order_id, commission_asset, time, is_buyer) %>%
  dplyr::rename(TxnPrice = price, TxnQty = qty, TxnFees = commission, TxnDate = time) %>% 
  dplyr::summarise(TxnPrice = mean(as.numeric(TxnPrice)), TxnQty = sum(as.numeric(TxnQty)),
                   TxnAmount = sum(as.numeric(quote_qty)), TxnFees = sum(as.numeric(TxnFees)),
                   TxnType = 'Trade') %>%
  dplyr::arrange(TxnDate)


final_trades <- combined_trades %>% full_join(transfers)
final_trades <- final_trades %>% arrange(TxnDate)


for (i in 1:nrow(final_trades)) { 
  
  CurrentDate = as.xts(final_trades$TxnDate[i])
  cat(".")
  # equity = getEndEq(ltaccount, CurrentDate)*.01
  ClosePrice = as.numeric(final_trades[i,]$TxnPrice)
  UnitSize = as.numeric(final_trades[i,]$TxnQty)
  
  # Check if TxnType is Trade
  if (final_trades[i,]$TxnType == 'Trade' ) {
    # If buying 
    if (final_trades[i,]$is_buyer == TRUE) { 
      cat('\n')
      # Store trade with blotter
      addTxn(ltportfolio, Symbol = final_trades[i,]$symbol , TxnDate = CurrentDate, TxnPrice = ClosePrice, TxnQty = UnitSize , TxnFees = 0, verbose = verbose)
    } else {
      # If selling
      if (final_trades[i,]$is_buyer == FALSE) {
        # Store trade with blotter
        cat('\n')
        addTxn(ltportfolio, Symbol = final_trades[i, ]$symbol, TxnDate = CurrentDate, TxnPrice = ClosePrice, TxnQty = -UnitSize , TxnFees = 0, verbose = verbose)
      }
    }
    updatePortf(ltportfolio, Symbols = final_trades[i,]$symbol, Prices = get(final_trades[i,]$symbol)[,"open"])
  } else {
    # Check if TxnType is Additions
    if (final_trades[i,]$TxnType == "Additions") {
      # Store trade with blotter
      cat('\n')
      addAcctTxn(ltaccount, TxnDate = CurrentDate, TxnType = final_trades[i,]$TxnType, Amount = final_trades[i,]$TxnAmount, verbose = verbose)
    } else {
      # Check if TxnType is Withdrawals
      if (final_trades[i,]$TxnType == "Withdrawals") {
        # Store trade with blotter
        cat('\n')
        addAcctTxn(ltaccount, TxnDate = CurrentDate, TxnType = final_trades[i,]$TxnType, Amount = final_trades[i,]$TxnAmount, verbose = verbose)
      }
    }
  }
  
  # Calculate P&L and Equity with blotter
  updateAcct(ltaccount)
  updateEndEq(ltaccount)
}

```

**Comment by Fayorsey** [comment]
@braverock I've also been getting the error messages below for context. Appreciate your help figuring things out. Please let me know if you have any suggestions for properly adding account transactions and recording portfolio transactions.

<img width="466" alt="Screen Shot 2023-04-13 at 10 15 17 AM" src="https://user-images.githubusercontent.com/76915445/231787340-caac8890-b4a0-450a-97fc-8e17ce1231de.png">

<img width="466" alt="Screen Shot 2023-04-13 at 10 15 32 AM" src="https://user-images.githubusercontent.com/76915445/231787363-3bcccbec-ff26-474d-8c18-49657e9ba870.png">
