### ISSUE TITLE
Failed to install 'blotter' from GitHub

### ISSUE THREAD

**Issue by dysfas** [braverock/blotter#122]
# I can't install this package #
> install.packages("devtools")
Installing package into ‘C:/Users/Monster/AppData/Local/R/win-library/4.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/devtools_2.4.5.zip'
Content type 'application/zip' length 435839 bytes (425 KB)
downloaded 425 KB

package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Monster\AppData\Local\Temp\Rtmp6RKqy8\downloaded_packages
> install.packages("FinancialInstrument")
Installing package into ‘C:/Users/Monster/AppData/Local/R/win-library/4.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/FinancialInstrument_1.3.1.zip'
Content type 'application/zip' length 547381 bytes (534 KB)
downloaded 534 KB

package ‘FinancialInstrument’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Monster\AppData\Local\Temp\Rtmp6RKqy8\downloaded_packages
> install.packages("PerformanceAnalytics") 
Installing package into ‘C:/Users/Monster/AppData/Local/R/win-library/4.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.3/PerformanceAnalytics_2.0.4.zip'
Content type 'application/zip' length 3114513 bytes (3.0 MB)
downloaded 3.0 MB

package ‘PerformanceAnalytics’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Monster\AppData\Local\Temp\Rtmp6RKqy8\downloaded_packages
> require(devtools)
Loading required package: devtools
Loading required package: usethis
> devtools::install_github("braverock/blotter")
Using GitHub PAT from the git credential store.
Error: Failed to install 'blotter' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 59/60
  Rate limit reset at: 2024-05-02 00:53:05 UTC

**Comment by peterccarl** [comment]
This is an issue with  your credentials and github, not the package.  Read the error message:
```
Using GitHub PAT from the git credential store.
Error: Failed to install 'blotter' from GitHub:
HTTP error 401.
**Bad credentials**
```
emphasis added.

**Comment by dysfas** [comment]
how can I solve problem about my credentials?

**Comment by jaymon0703** [comment]
See https://stackoverflow.com/a/70912727 good luck

**Comment by dysfas** [comment]
thank you so much

**Comment by jaymon0703** [comment]
You're welcome.

Thank you Peter Carl for the inspiration.
