### ISSUE TITLE
[R-Forge #2190] handle incorrect updatePosPL 'Dates' string more safely (was: a bug in updatePosPL.R in quantstrat)

### ISSUE THREAD

**Issue by joshuaulrich** [braverock/blotter#20]
Submitted by: Alex Lee
Assigned to: Nobody
[R-Forge link](http://r-forge.r-project.org/tracker/index.php?func=detail&aid=2190&group_id=316&atid=1269)

At line 42-44 in updatePosPL.R

```r
if(.parseISO8601(Dates)$first.time < as.POSIXct(first(index(prices))) || is.na(.parseISO8601(Dates)$first.time)){
    Dates<-index(prices[paste('/',.parseISO8601(Dates)$last.time,sep='')])
}
```

If `.parseISO8601(Dates)$last.time` returns `NA`, the `[.xts` will be called with `'/NA'`, the execution stops.

I change this line to:

```r
last.time <- .parseISO8601(Dates)$last.time
if (is.na(last.time)) last.time=NULL 
```

This should be correct.

**Comment by braverock** [comment]
I'm inclined to close this.  Having a problem here is an incorrect xts subset, so basically user error.

In current code, there are more checks for valid data than there were when this was reported.

The current code has  the lines in this report at 46-49

On the other hand, this is already in the checks to try to catch user error, so making it even more robust might be a good idea, but that nested check is already hard to parse.
