### ISSUE TITLE
[R-Forge #4985] getAccount and getPortfolio return environments

### ISSUE THREAD

**Issue by joshuaulrich** [braverock/blotter#21]
Submitted by: Joshua Ulrich
Assigned to: Nobody
[R-Forge link](http://r-forge.r-project.org/tracker/index.php?func=detail&aid=4985&group_id=316&atid=1269)

These functions return the actual account and portfolio environments, which means changes to the returned object directly affect the .blotter environment.  Instead, these functions should return lists, by wrapping the environment in an as.list() call.

The current ability of these functions should be encapsulated in new functions (.getAccount and .getPortfolio) and not exported.

**Comment by braverock** [comment]
closed. fixed.

.getPortfolio was implemented, and getPortfolio returns a copy.

getAccount also returns a copy, but does not call a .getAccount helper function.
