### ISSUE TITLE
[R-Forge #5797] bug in addTxn/updatePortf?

### ISSUE THREAD

**Issue by joshuaulrich** [braverock/blotter#22]
Submitted by: Phong Nguyen
Assigned to: Nobody
[R-Forge link](http://r-forge.r-project.org/tracker/index.php?func=detail&aid=5797&group_id=316&atid=1269)

Hello,

I use blotter to track/simulate portfolio to replay data from an actual transactions but ran into a problem that I'm not sure if it's a subtle bug with regards to timezone or something else, as only 2/163 transactions cause issue. Details of problematic transactions are below:
- on 2014-03-28, I bought 530 FPT
- on 2014-05-09, this has 4:1 stock split, which is simulated by adding to the portfolio 132 (530/4, rounding to nearest integer) with price of 0. The total position in portfolio should be 662 (shown correctly from getPos on 2014-05-27)
- on 2014-03-28, I bought another 1250 FPT, the total should be 1912, but getPos shows only 1780 (=530+1250).

Any ideas/help for work-around is highly appreciated. Many thanks in advance.

[1] '2014-03-28 00:00:00 FPT 530 @ 69.5'
[1] '2014-05-28 00:00:00 FPT 1250 @ 46.1'
[1] '2014-05-29 00:00:00 FPT -530 @ 47.1'
[1] '2014-06-12 00:00:00 FPT -1250 @ 47.3'
[1] '2014-07-03 00:00:00 FPT -130 @ 48.2'
[1] '2014-05-09 00:00:00 FPT 132 @ 0.000'
[1] '2014-05-09 FPT Dividend 1.425 on 662 shares: 943.35'

> getPos(Portfolio=portfolio.VNDS,Symbol='FPT',Date=as.Date('2014-05-27'))
>            Pos.Qty     Pos.Avg.Cost
> 2014-05-12     662 55.6419939577039
> getPos(Portfolio=portfolio.VNDS,Symbol='FPT',Date=as.Date('2014-05-28'))
>                     Pos.Qty     Pos.Avg.Cost
> 2014-05-28 07:00:00    1780 53.0674157303371
> getPos(Portfolio=portfolio.VNDS,Symbol='FPT',Date=as.Date('2014-05-29'))
>                     Pos.Qty     Pos.Avg.Cost
> 2014-05-29 07:00:00    1250 53.0674157303371
> getPos(Portfolio=portfolio.VNDS,Symbol='FPT',Date=as.Date('2014-05-30'))
>                     Pos.Qty     Pos.Avg.Cost
> 2014-05-29 07:00:00    1250 53.0674157303371
> 
> sessionInfo()
> R version 3.0.3 (2014-03-06)
> Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252  
[3] LC_MONETARY=English_Australia.1252 LC_NUMERIC=C  
[5] LC_TIME=English_Australia.1252    

attached base packages:
[1] grDevices datasets  parallel  graphics  utils     stats     methods  
[8] base     

other attached packages:
 [1] XML_3.98-1.1               vTrading_0.2.496  
 [3] scales_0.2.4               ggplot2_1.0.0  
 [5] reshape2_1.4               png_0.1-7  
 [7] plyr_1.8.1                 timeDate_3010.98  
 [9] logging_0.7-103            quantstrat_0.8.2  
[11] foreach_1.4.2              gdata_2.13.3  
[13] blotter_0.8.18             PerformanceAnalytics_1.1.0
[15] FinancialInstrument_1.1    quantmod_0.4-0  
[17] TTR_0.22-0                 xts_0.9-7  
[19] zoo_1.7-11                 Defaults_1.1-1            

loaded via a namespace (and not attached):
 [1] codetools_0.2-8  colorspace_1.2-4 digest_0.6.4     grid_3.0.3  
 [5] gtable_0.1.2     gtools_3.4.1     iterators_1.0.7  labeling_0.2  
 [9] lattice_0.20-29  MASS_7.3-33      munsell_0.4.2    proto_0.3-10  
[13] Rcpp_0.11.2      stringr_0.6.2    tools_3.0.3     

P/S: I tried to submit to forum but it doesn't seem to get registered

**Comment by braverock** [comment]
closing as not reproducible

**Comment by joshuaulrich** [comment]
Reopening, as I can reproduce with the current head of master.

```r
require(blotter)
Sys.setenv(TZ = "UTC")
currency("USD")
stock("FPT", currency = "USD")
initPortf("split", "FPT")
addTxn("split", "FPT", "2014-03-28", 530, 69.5)
addTxn("split", "FPT", "2014-05-28", 1250, 46.1)
addTxn("split", "FPT", "2014-05-29", -530, 47.1)
addTxn("split", "FPT", "2014-06-12", -1250, 47.3)
addTxn("split", "FPT", "2014-07-03", -130, 48.2)
addTxn("split", "FPT", "2014-05-09", 132, 0.000)
addDiv("split", "FPT", "2014-05-09", 1.425) # on 662 shares: 943.35"

getPos("split", "FPT", "2014-05-27")
#            Pos.Qty Pos.Avg.Cost
# 2014-05-09     662     55.64199
getPos("split", "FPT", "2014-05-28")
#            Pos.Qty Pos.Avg.Cost
# 2014-05-28    1780     53.06742
getPos("split", "FPT", "2014-05-29")
#            Pos.Qty Pos.Avg.Cost
# 2014-05-29    1250     53.06742
getPos("split", "FPT", "2014-05-30")
#            Pos.Qty Pos.Avg.Cost
# 2014-05-29    1250     53.06742

getTxns("split", "FPT")
#            Txn.Qty Txn.Price Txn.Fees Txn.Value Txn.Avg.Cost Net.Txn.Realized.PL
# 1950-01-01       0       0.0        0      0.00        0.000                0.00
# 2014-03-28     530      69.5        0  36835.00       69.500                0.00
# 2014-05-09     132       0.0        0      0.00        0.000                0.00
# 2014-05-09       0       0.0        0   -943.35        1.425              943.35
# 2014-05-28    1250      46.1        0  57625.00       46.100                0.00
# 2014-05-29    -530      47.1        0 -24963.00       47.100            -3162.73
# 2014-06-12   -1250      47.3        0 -59125.00       47.300            -7209.27
# 2014-07-03    -130      48.2        0  -6266.00       48.200                0.00
```

Results seem correct if `addTxn` is called in the same order as the dates of the transactions.

```r
require(blotter)
Sys.setenv(TZ = "UTC")
currency("USD")
stock("FPT", currency = "USD")
initPortf("split", "FPT")
addTxn("split", "FPT", "2014-03-28", 530, 69.5)
addTxn("split", "FPT", "2014-05-09", 132, 0.000)
addDiv("split", "FPT", "2014-05-09", 1.425) # on 662 shares: 943.35"
addTxn("split", "FPT", "2014-05-28", 1250, 46.1)
addTxn("split", "FPT", "2014-05-29", -530, 47.1)
addTxn("split", "FPT", "2014-06-12", -1250, 47.3)
addTxn("split", "FPT", "2014-07-03", -130, 48.2)

getPos("split", "FPT", "2014-05-27")
#            Pos.Qty Pos.Avg.Cost
# 2014-05-09     662     55.64199
getPos("split", "FPT", "2014-05-28")
#            Pos.Qty Pos.Avg.Cost
# 2014-05-28    1912     49.40377
getPos("split", "FPT", "2014-05-29")
#            Pos.Qty Pos.Avg.Cost
# 2014-05-29    1382     49.40377
getPos("split", "FPT", "2014-05-30")
#            Pos.Qty Pos.Avg.Cost
# 2014-05-29    1382     49.40377

getTxns("split", "FPT")
#            Txn.Qty Txn.Price Txn.Fees Txn.Value Txn.Avg.Cost Net.Txn.Realized.PL
# 1950-01-01       0       0.0        0      0.00        0.000              0.0000
# 2014-03-28     530      69.5        0  36835.00       69.500              0.0000
# 2014-05-09     132       0.0        0      0.00        0.000              0.0000
# 2014-05-09       0       0.0        0   -943.35        1.425            943.3500
# 2014-05-28    1250      46.1        0  57625.00       46.100              0.0000
# 2014-05-29    -530      47.1        0 -24963.00       47.100          -1220.9958
# 2014-06-12   -1250      47.3        0 -59125.00       47.300          -2629.7071
# 2014-07-03    -130      48.2        0  -6266.00       48.200           -156.4895
```

**Comment by braverock** [comment]
addTxn *must* be called in order.  

All per-transaction accounting is done on adding transactions to the Txn slot.  Calling them out of order messes that up, which is why we don't allow it.

**Comment by joshuaulrich** [comment]
> `addTxn` must be called in order.

This should be documented in `?addTxn`.

> ...which is why we don't allow it.

But it *is* allowed.  The OP's example does it.

I'm going to add this to the documentation, and add a check to `addTxn` that will throw an error if there's an attempt to add an out-of-order transaction.

**Comment by braverock** [comment]
Sounds good.

There is a note in the blotter-package documentation that

> Trades must be made in date order.

But I agree that putting more explicit guidance in the `addTxn` documentation makes sese, as does adding an error check.

**Comment by joshuaulrich** [comment]
Fixed in https://github.com/braverock/blotter/commit/24b578628415111885d29ef97d5ab0eed1c7bb75. Closing.
