### ISSUE TITLE
Test to ensure transaction time-order fails for objects with Date index

### ISSUE THREAD

**Issue by joshuaulrich** [braverock/blotter#51]
Transactions should always be added to the portfolio in time-order.  Strange behavior can occur if they're added out of order.  But the blotter 'txn' table is always a `POSIXct` index, so the comparison fails if the user supplies data with a `Date` index.

```r
require(blotter)
currency("USD")
initPortf("test", symbols="AAPL", currency="USD")

addTxn("test", "AAPL", as.Date("2017-01-01"),  1, 10)
# [1] "2017-01-01 00:00:00 AAPL 1 @ 10"
# Warning messages:
# 1: In addTxn("test", "AAPL", as.Date("2017-01-01"), 1, 10) :
#   Incompatible methods ("Ops.Date", "Ops.POSIXt") for "<"
# 2: In getInstrument(Symbol) :
#   instrument AAPL not found, please create it first.
# 3: In addTxn("test", "AAPL", as.Date("2017-01-01"), 1, 10) :
#   Instrument AAPL  not found, using contract multiplier of 1
addTxn("test", "AAPL", as.Date("2017-01-02"), -1, 10)
# Error in addTxn("test", "AAPL", as.Date("2017-01-02"), -1, 10) : 
#   Transactions must be added in order. TxnDate (2017-01-02) is before last transaction in portfolio (2016-# 12-31 18:00:00) for AAPL
# In addition: Warning message:
# In addTxn("test", "AAPL", as.Date("2017-01-02"), -1, 10) :
#   Incompatible methods ("Ops.Date", "Ops.POSIXt") for "<"
```

**Comment by davidkleman** [comment]
Having some issues related to this. Are multiple transactions on the same Date supposed to work? In that case I'd like to repor the behaviour below. I tried converting manually to Posix but same behaviour. Apparently multiple transactions in one instrument goes through on one date (2007-08-08) but not the next day. 

[1] "2007-07-20 02:00:00 FIRE -100 @ 23.4"
[1] "2007-07-23 02:00:00 WESC -50 @ 80"
[1] "2007-07-30 02:00:00 FIRE -25 @ 22.6"
[1] "2007-07-31 02:00:00 WESC -100 @ 80"
[1] "2007-08-08 02:00:00 CONS 100 @ 55.25"
[1] "2007-08-08 02:00:00 CONS 300 @ 55.25"
[1] "2007-08-08 02:00:00 SAND 200 @ 137.75"
[1] "2007-08-09 02:00:00 CONS -300 @ 54"
[1] "2007-08-09 02:00:00 CONS -300 @ 54"
Error in addTxn(myPortfolio.str, row$Ticker1st, TxnDate = row$PosixDate,  : 
  Transactions must be added in order. TxnDate (2007-08-09 02:00:00) is before last transaction in portfolio (2007-08-09 02:00:00) for CONS

**Comment by braverock** [comment]
@davidkleman I'm not sure your issue is related to this (closed) bug.

In any event, if you have multiple transactions on the same Date, presumably you know the time the transaction occurred?  Why not put in the transactions as it/they actually happened rather than throwing away the time information?

**Comment by davidkleman** [comment]
Yes, me neither. New to open source, am I supposed to write about this in some other way or place?

Unfortunately my broker only delivers the date of the transactions. As my use case is to analyze my manual trades which I haven't logged exact times for I don't know those. 

In case someone encounters a similar situtation: Separating the transactions in time using row_number allows them to be added. E.g. `stock_trans <- stock_trans %>% group_by(Ticker1st, PosixDate) %>% mutate(AdjDate = PosixDate + seconds(row_number())) %>% ungroup() %>% arrange(Ticker1st, AdjDate)`

**Comment by braverock** [comment]
@davidkleman , see 

```r
?make.index.unique
```

for a much easier way to create a unique index without converting out of the `xts` time series and doing all the backflips you are doing. 

In your example, assuming `stock_trans` is your time series of transactions, it would be simply

```r
make.index.unique(stock_trans)
```

**Comment by davidkleman** [comment]
Neat, very neat - thank you. Backflips are dangerous.

**Comment by jaymon0703** [comment]
Safer in a swimming pool, but still dangerous
