### ISSUE TITLE
Optimise building replicate transactions

### ISSUE THREAD

**Issue by jaymon0703** [braverock/blotter#65]
Using a vectorised approach for the construction of the replicate transactions in txnsim.txns() we can reduce the memory required to simulate 'n' replicates. The improvement in performance will be orders of magnitude, making the simulation of 1k replicates possible in the single digit minute time space (currently ranging from 20 mins to 15 hours depending on hardware) and making feasible simulations for a greater number of replicates.

**Comment by braverock** [comment]
Closing as fixed.
