### ISSUE TITLE
question:   how to get a series of Pos.Qty via a function?

### ISSUE THREAD

**Issue by ssh352** [braverock/blotter#75]
<img width="1021" alt="screen shot 2019-01-30 at 2 58 48 pm" src="https://user-images.githubusercontent.com/41779116/51964162-a437d300-24a0-11e9-9f98-012178f0e33f.png">

 getTxns excludes a few columns from txns, though Pos.Qty is there.

**Comment by jaymon0703** [comment]
Hi @ssh352 have you looked at perTradeStats()? Cumsum of Txn.Qty is also an option if you want to use the output of getTxns().

**Comment by ssh352** [comment]
thank you both work~
